version: '3.1'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: jose
      POSTGRES_PASSWORD: jnh76bgs_874hjf
      POSTGRES_DB: pruebaSQL2
      PGDATA: /data/postgres
    volumes:
       - /postgresVolume:/data/postgres      
    ports:
       - "13229:5432"    
    restart: unless-stopped