version: '3'

services:
  certbot:
      image: certbot/certbot
      container_name: certbot
      volumes:
        - certbot-etc:/etc/letsencrypt
        - /dist:/var/www/html
      command: certonly --webroot --webroot-path=/dist --email geekscalada@gmail.com --agree-tos --no-eff-email --staging -d joseescalada.com -d www.joseescalada.com
