version: '3'

services:
  certbot:
      image: certbot/certbot
      container_name: certbot
      volumes:
        - ./certbot-etc:/etc/letsencrypt
        - /dist:/var/www/html
      #command: certonly --webroot --webroot-path=/dist --email yourmail@mail.com --agree-tos --no-eff-email --staging -d yourdomain.com -d www.yourdomain.com
      command: certonly --webroot --webroot-path=/var/www/html --email yourmail@mail.com --agree-tos --no-eff-email --force-renewal -d yourdomain.com -d www.yourdomain.com
